export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-gray-400 p-8 md:p-24 font-sans leading-relaxed">
      <div className="max-w-3xl mx-auto space-y-8">
        <h1 className="text-4xl font-black text-white italic uppercase tracking-tighter">Terms of Service</h1>
        <p className="text-sm border-l-2 border-blue-500 pl-4 py-2 bg-blue-500/5 text-blue-200">
          Our order process is conducted by our online reseller Paddle.com. Paddle.com is the Merchant of Record for all our orders. Paddle provides all customer service inquiries and handles returns.
        </p>
        
        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">1. Acceptance of Terms</h2>
          <p>By accessing Neural Capacity, you agree to be bound by these terms. We provide AI-driven coding enhancements and workspace management tools.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">2. User Conduct</h2>
          <p>You agree not to use Neural Capacity for any unlawful activities or to upload malicious code. We reserve the right to terminate accounts that violate our security protocols.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">3. Intellectual Property</h2>
          <p>All code generated by our AI remains your property. However, the Neural Capacity platform, UI, and underlying algorithms are the exclusive property of our company.</p>
        </section>
        
        <footer className="pt-12 text-[10px] uppercase tracking-widest opacity-50">
          Last Updated: March 2024 • Neural Capacity
        </footer>
      </div>
    </div>
  )
}
