export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-gray-400 p-8 md:p-24 font-sans leading-relaxed">
      <div className="max-w-3xl mx-auto space-y-8">
        <h1 className="text-4xl font-black text-white italic uppercase tracking-tighter">Terms of Service</h1>
        
        <p className="text-sm border-l-2 border-amber-500 pl-4 py-2 bg-amber-500/5 text-amber-200">
          <strong>Cryptocurrency Notice:</strong> All subscription payments are handled via decentralized blockchain networks. You are solely responsible for ensuring transactions are sent to the correct address on the correct network.
        </p>
        
        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">1. Acceptance of Terms</h2>
          <p>By accessing Neural Node, you agree to be bound by these terms. We provide AI-driven code synchronization, workspace memory, and webhook integrations.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">2. Payment Responsibilities</h2>
          <p>When purchasing compute power or tier upgrades, you agree to bear all associated network fees (gas). Neural Node is not liable for lost funds due to user error, including but not limited to interacting with fraudulent contracts or sending unsupported tokens.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">3. User Conduct</h2>
          <p>You agree not to use Neural Node to process, store, or distribute malicious code. We reserve the right to sever API access and terminate nodes that violate our security protocols without refund.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-bold text-white">4. Intellectual Property</h2>
          <p>All source code analyzed or generated by our AI remains your property. However, the Neural Node platform, the webhook engines, UI, and underlying sync algorithms are our exclusive property.</p>
        </section>
        
        <footer className="pt-12 text-[10px] uppercase tracking-widest opacity-50">
          Last Updated: Neural Node • Current Epoch
        </footer>
      </div>
    </div>
  )
}
